import {StyleSheet} from 'react-native';

import COLORS from './colors';

const styles = StyleSheet.create({
  //please short from a to z or by categori if adding styles

  //Single Styles
  alItCenter: {alignItems: 'center'},
  alItEnd: {alignItems: 'flex-end'},
  br0: {borderRadius: 0},
  br10: {borderRadius: 10},
  fx1: {flex: 1},
  fx3: {flex: 3},
  fx4: {flex: 4},
  fxg1: {flexGrow: 1},
  fxdRow: {flexDirection: 'row'},
  gap4: {gap: 4},
  gap8: {gap: 8},
  gap12: {gap: 12},
  gap16: {gap: 16},
  gap20: {gap: 20},
  gap24: {gap: 24},
  gap32: {gap: 32},
  jusContSpbtw: {justifyContent: 'space-between'},
  jusContCntr: {justifyContent: 'center'},
  jusContFxStart: {justifyContent: 'flex-start'},
  jusContFxEnd: {justifyContent: 'flex-end'},
  mr0: {margin: 0},
  mr8: {margin: 8},
  mr12: {margin: 12},
  mr16: {margin: 16},
  mrb4: {marginBottom: 4},
  mrb6: {marginBottom: 6},
  mrb8: {marginBottom: 8},
  mrb12: {marginBottom: 12},
  mrb16: {marginBottom: 16},
  mrb20: {marginBottom: 20},
  mrb24: {marginBottom: 24},
  mrb32: {marginBottom: 32},
  mrb36: {marginBottom: 36},
  mrh4: {marginHorizontal: 4},
  mrh6: {marginHorizontal: 6},
  mrh8: {marginHorizontal: 8},
  mrh12: {marginHorizontal: 12},
  mrh16: {marginHorizontal: 16},
  mrl4: {marginLeft: 4},
  mrl6: {marginLeft: 6},
  mrl8: {marginLeft: 8},
  mrl12: {marginLeft: 12},
  mrl16: {marginLeft: 16},
  mrr4: {marginRight: 4},
  mrr6: {marginRight: 6},
  mrr8: {marginRight: 8},
  mrr12: {marginRight: 12},
  mrr16: {marginRight: 16},
  mrr20: {marginRight: 20},
  mrt4: {marginTop: 4},
  mrt8: {marginTop: 8},
  mrt12: {marginTop: 12},
  mrt16: {marginTop: 16},
  mrt24: {marginTop: 24},
  mrt40: {marginTop: 40},
  mrv8: {marginVertical: 8},
  mrv16: {marginVertical: 16},
  pd0: {padding: 0},
  pd4: {padding: 4},
  pd8: {padding: 8},
  pd10: {padding: 10},
  pd12: {padding: 12},
  pd16: {padding: 16},
  pd20: {padding: 20},
  pdh0: {paddingHorizontal: 0},
  pdh8: {paddingHorizontal: 8},
  pdh12: {paddingHorizontal: 12},
  pdh16: {paddingHorizontal: 16},
  pdh20: {paddingHorizontal: 20},
  pdh24: {paddingHorizontal: 24},

  pdt12: {paddingTop: 12},
  pdv8: {paddingVertical: 8},
  pdv12: {paddingVertical: 12},
  pdv16: {paddingVertical: 16},
  pdv20: {paddingVertical: 20},
  pdv24: {paddingVertical: 24},
  pdb12: {paddingBottom: 12},
  pdb50: {paddingBottom: 50},
  pdb100: {paddingBottom: 100},
  row: {flexDirection: 'row'},
  txtCapitalize: {textTransform: 'capitalize'},
  txtDecLineT: {textDecorationLine: 'line-through'},
  txtLowercase: {textTransform: 'lowercase'},
  txtUppercase: {textTransform: 'uppercase'},
  txtAlignCenter: {textAlign: 'center'},
  txtAlignRight: {textAlign: 'right'},
  wAuto: {width: 'auto'},
  w50: {width: '50%'},
  w100: {width: '100%'},
  h100: {height: '100%'},

  //Custom Styles
  rowAlgCenter: {flexDirection: 'row', alignItems: 'center'},
  shadow: {
    shadowColor: COLORS.black_100,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowRadius: 2,
    shadowOpacity: 0.2,
    elevation: 6,
  },
});

export default styles;
